<?php

/**
 * BaseServiceCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $body
 * @property Doctrine_Collection $Service
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method clob                getBody()    Returns the current record's "body" value
 * @method Doctrine_Collection getService() Returns the current record's "Service" collection
 * @method ServiceCategory     setName()    Sets the current record's "name" value
 * @method ServiceCategory     setBody()    Sets the current record's "body" value
 * @method ServiceCategory     setService() Sets the current record's "Service" collection
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceCategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Service', array(
             'local' => 'id',
             'foreign' => 'service_category_id'));
    }
}