<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property integer $service_category_id
 * @property boolean $is_active
 * @property ServiceCategory $ServiceCategory
 * 
 * @method string          getName()                Returns the current record's "name" value
 * @method clob            getDescription()         Returns the current record's "description" value
 * @method integer         getServiceCategoryId()   Returns the current record's "service_category_id" value
 * @method boolean         getIsActive()            Returns the current record's "is_active" value
 * @method ServiceCategory getServiceCategory()     Returns the current record's "ServiceCategory" value
 * @method Service         setName()                Sets the current record's "name" value
 * @method Service         setDescription()         Sets the current record's "description" value
 * @method Service         setServiceCategoryId()   Sets the current record's "service_category_id" value
 * @method Service         setIsActive()            Sets the current record's "is_active" value
 * @method Service         setServiceCategory()     Sets the current record's "ServiceCategory" value
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseService extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('service_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ServiceCategory', array(
             'local' => 'service_category_id',
             'foreign' => 'id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $this->actAs($dmsortable0);
    }
}