<?php

/**
 * BaseAboutSlideshow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property clob $description
 * @property boolean $is_active
 * 
 * @method string         getTitle()       Returns the current record's "title" value
 * @method string         getSubtitle()    Returns the current record's "subtitle" value
 * @method clob           getDescription() Returns the current record's "description" value
 * @method boolean        getIsActive()    Returns the current record's "is_active" value
 * @method AboutSlideshow setTitle()       Sets the current record's "title" value
 * @method AboutSlideshow setSubtitle()    Sets the current record's "subtitle" value
 * @method AboutSlideshow setDescription() Sets the current record's "description" value
 * @method AboutSlideshow setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAboutSlideshow extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('about_slideshow');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $dmsortable0 = new Doctrine_Template_DmSortable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($dmsortable0);
        $this->actAs($timestampable0);
    }
}