<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property integer $logo
 * @property boolean $is_active
 * @property DmMedia $Logo
 * @property Doctrine_Collection $Project
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method integer             getLogo()        Returns the current record's "logo" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method DmMedia             getLogo()        Returns the current record's "Logo" value
 * @method Doctrine_Collection getProject()     Returns the current record's "Project" collection
 * @method Client              setTitle()       Sets the current record's "title" value
 * @method Client              setDescription() Sets the current record's "description" value
 * @method Client              setLogo()        Sets the current record's "logo" value
 * @method Client              setIsActive()    Sets the current record's "is_active" value
 * @method Client              setLogo()        Sets the current record's "Logo" value
 * @method Client              setProject()     Sets the current record's "Project" collection
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('logo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Logo', array(
             'local' => 'logo',
             'foreign' => 'id'));

        $this->hasMany('Project', array(
             'local' => 'id',
             'foreign' => 'client'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $this->actAs($dmsortable0);
    }
}