<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $body
 * @property Doctrine_Collection $Project
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method clob                getBody()    Returns the current record's "body" value
 * @method Doctrine_Collection getProject() Returns the current record's "Project" collection
 * @method Category            setName()    Sets the current record's "name" value
 * @method Category            setBody()    Sets the current record's "body" value
 * @method Category            setProject() Sets the current record's "Project" collection
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}