<?php

/**
 * BaseStaffMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property enum $department
 * @property clob $bio
 * @property integer $photo
 * @property boolean $is_active
 * @property DmMedia $Photo
 * 
 * @method string      getName()       Returns the current record's "name" value
 * @method string      getTitle()      Returns the current record's "title" value
 * @method enum        getDepartment() Returns the current record's "department" value
 * @method clob        getBio()        Returns the current record's "bio" value
 * @method integer     getPhoto()      Returns the current record's "photo" value
 * @method boolean     getIsActive()   Returns the current record's "is_active" value
 * @method DmMedia     getPhoto()      Returns the current record's "Photo" value
 * @method StaffMember setName()       Sets the current record's "name" value
 * @method StaffMember setTitle()      Sets the current record's "title" value
 * @method StaffMember setDepartment() Sets the current record's "department" value
 * @method StaffMember setBio()        Sets the current record's "bio" value
 * @method StaffMember setPhoto()      Sets the current record's "photo" value
 * @method StaffMember setIsActive()   Sets the current record's "is_active" value
 * @method StaffMember setPhoto()      Sets the current record's "Photo" value
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaffMember extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('staff_member');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('department', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Design',
              1 => 'Project Management',
              2 => 'Technology',
              3 => 'User Experience Design/IA',
             ),
             ));
        $this->hasColumn('bio', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('photo', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Photo', array(
             'local' => 'photo',
             'foreign' => 'id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $this->actAs($dmsortable0);
    }
}