<?php

/**
 * BaseProjectVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $url
 * @property clob $body
 * @property integer $project
 * @property boolean $is_featured
 * @property boolean $is_active
 * @property Project $Project
 * 
 * @method string       getName()        Returns the current record's "name" value
 * @method string       getUrl()         Returns the current record's "url" value
 * @method clob         getBody()        Returns the current record's "body" value
 * @method integer      getProject()     Returns the current record's "project" value
 * @method boolean      getIsFeatured()  Returns the current record's "is_featured" value
 * @method boolean      getIsActive()    Returns the current record's "is_active" value
 * @method Project      getProject()     Returns the current record's "Project" value
 * @method ProjectVideo setName()        Sets the current record's "name" value
 * @method ProjectVideo setUrl()         Sets the current record's "url" value
 * @method ProjectVideo setBody()        Sets the current record's "body" value
 * @method ProjectVideo setProject()     Sets the current record's "project" value
 * @method ProjectVideo setIsFeatured()  Sets the current record's "is_featured" value
 * @method ProjectVideo setIsActive()    Sets the current record's "is_active" value
 * @method ProjectVideo setProject()     Sets the current record's "Project" value
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectVideo extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_video');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('project', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('is_featured', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project',
             'foreign' => 'id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $this->actAs($dmsortable0);
    }
}