generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: AboutSlideshow
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: about_slideshow
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - subtitle
          - description
          - is_active
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - is_active
          - subtitle
          - description
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Description: [description]
          Others: [subtitle]
        class: AboutSlideshowAdminForm
        fields: {  }
      edit: ~
      new: ~
