generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: JobApplication
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: job_application
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - resume
          - job_position_id
          - first_name
          - last_name
          - address
          - city
          - state
          - zip
          - phone
          - email
          - website
          - objective
          - links
          - cover_letter
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - first_name
          - last_name
          - job_position_id
          - address
          - city
          - state
          - zip
          - phone
          - email
          - website
          - resume
          - objective
          - links
          - cover_letter
          - created_at
          - updated_at
      form:
        display:
          NONE: [job_position_id]
          Resume: [resume_form, resume_view]
          Objective: [objective]
          Links: [links]
          'Cover letter': [cover_letter]
          Others: [first_name, last_name, address, city, state, zip, phone, email, website]
        class: JobApplicationAdminForm
        fields: {  }
      edit: ~
      new: ~
