<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('about_slideshow', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'subtitle' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'body' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('client', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '120',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'logo' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('job_application', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'job_position_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'address' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'state' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => '--',
              1 => 'AL',
              2 => 'AZ',
              3 => 'AR',
              4 => 'CA',
              5 => 'CO',
              6 => 'CT',
              7 => 'DE',
              8 => 'FL',
              9 => 'GA',
              10 => 'HI',
              11 => 'IA',
              12 => 'ID',
              13 => 'IL',
              14 => 'IN',
              15 => 'KS',
              16 => 'KY',
              17 => 'LA',
              18 => 'MA',
              19 => 'ME',
              20 => 'MD',
              21 => 'MI',
              22 => 'MN',
              23 => 'MO',
              24 => 'MS',
              25 => 'MT',
              26 => 'NE',
              27 => 'NC',
              28 => 'ND',
              29 => 'NJ',
              30 => 'NM',
              31 => 'NV',
              32 => 'NY',
              33 => 'OH',
              34 => 'OK',
              35 => 'OR',
              36 => 'PA',
              37 => 'RI',
              38 => 'SC',
              39 => 'SD',
              40 => 'TN',
              41 => 'TX',
              42 => 'UT',
              43 => 'VA',
              44 => 'VT',
              45 => 'WA',
              46 => 'WI',
              47 => 'WV',
              48 => 'WY',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'zip' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'website' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'resume' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'objective' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'links' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'cover_letter' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('job_position', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'department' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Design',
              1 => 'Project Management',
              2 => 'Technology',
              3 => 'User Experience Design/IA',
              ),
              'length' => '',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'qualifications' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'tech_experience' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'additional_areas' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'required_skills' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'time_reqs' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('page', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'body' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'photo' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '120',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'overview' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'extra' => 'markdown',
              'length' => '2000',
             ),
             'launch_date' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '60',
             ),
             'url' => 
             array(
              'type' => 'string',
              'extra' => 'link',
              'length' => '200',
             ),
             'awards' => 
             array(
              'type' => 'string',
              'extra' => 'markdown',
              'length' => '500',
             ),
             'screenshot' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'thumbnail' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'client' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'client_2' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'client_3' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'is_featured' => 
             array(
              'type' => 'boolean',
              'notnull' => '',
              'default' => '0',
              'length' => '25',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project_video', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'body' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'project' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'is_featured' => 
             array(
              'type' => 'boolean',
              'notnull' => '',
              'default' => '0',
              'length' => '25',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('service', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'service_category_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('service_category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'body' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('staff_member', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'department' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'Design',
              1 => 'Project Management',
              2 => 'Technology',
              3 => 'User Experience Design/IA',
              ),
              'length' => '',
             ),
             'bio' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'photo' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('page_dm_tag', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'dm_tag_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'dm_tag_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project_dm_tag', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'dm_tag_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'dm_tag_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('project_dm_media', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
              'autoincrement' => '1',
             ),
             'dm_media_id' => 
             array(
              'notnull' => '1',
              'type' => 'integer',
              'length' => '8',
             ),
             'dm_record_id' => 
             array(
              'notnull' => '1',
              'unsigned' => '',
              'type' => 'integer',
              'length' => '8',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'indexes' => 
             array(
              'record_dm_media' => 
              array(
              'fields' => 
              array(
               0 => 'dm_record_id',
               1 => 'dm_media_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('dm_contact', 'email_subject', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_contact', 'email_category', 'enum', '', array(
             'values' => 
             array(
              0 => 'New Business',
              1 => 'Original Content',
              2 => 'Other',
             ),
             ));
        $this->addColumn('dm_contact', 'other_desc', 'string', '255', array(
             ));
        $this->addColumn('dm_contact', 'phone', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_user', 'description', 'clob', '', array(
             'extra' => 'markdown',
             ));
        $this->addColumn('dm_user', 'photo', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('about_slideshow');
        $this->dropTable('category');
        $this->dropTable('client');
        $this->dropTable('job_application');
        $this->dropTable('job_position');
        $this->dropTable('page');
        $this->dropTable('project');
        $this->dropTable('project_video');
        $this->dropTable('service');
        $this->dropTable('service_category');
        $this->dropTable('staff_member');
        $this->dropTable('page_dm_tag');
        $this->dropTable('project_dm_tag');
        $this->dropTable('project_dm_media');
        $this->removeColumn('dm_contact', 'email_subject');
        $this->removeColumn('dm_contact', 'email_category');
        $this->removeColumn('dm_contact', 'other_desc');
        $this->removeColumn('dm_contact', 'phone');
        $this->removeColumn('dm_user', 'description');
        $this->removeColumn('dm_user', 'photo');
    }
}