<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('project', 'extract', 'string', '300', array(
             'notnull' => '',
             'extra' => 'markdown',
             ));
    }

    public function down()
    {
        $this->removeColumn('project', 'extract');
    }
}