<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('project', 'launch_date', 'string', '60', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}