<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('client', 'client_logo_dm_media_id');
        $this->createForeignKey('client', 'client_logo_dm_media_id_1', array(
             'name' => 'client_logo_dm_media_id_1',
             'local' => 'logo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('client', 'client_logo', array(
             'fields' => 
             array(
              0 => 'logo',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('client', 'client_logo_dm_media_id', array(
             'name' => 'client_logo_dm_media_id',
             'local' => 'logo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->dropForeignKey('client', 'client_logo_dm_media_id_1');
        $this->removeIndex('client', 'client_logo', array(
             'fields' => 
             array(
              0 => 'logo',
             ),
             ));
    }
}