<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('client', 'client_logo_dm_media_id', array(
             'name' => 'client_logo_dm_media_id',
             'local' => 'logo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('dm_user', 'dm_user_photo_dm_media_id', array(
             'name' => 'dm_user_photo_dm_media_id',
             'local' => 'photo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('job_application', 'job_application_resume_dm_media_id', array(
             'name' => 'job_application_resume_dm_media_id',
             'local' => 'resume',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('job_application', 'job_application_job_position_id_job_position_id', array(
             'name' => 'job_application_job_position_id_job_position_id',
             'local' => 'job_position_id',
             'foreign' => 'id',
             'foreignTable' => 'job_position',
             ));
        $this->createForeignKey('page', 'page_photo_dm_media_id', array(
             'name' => 'page_photo_dm_media_id',
             'local' => 'photo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('project', 'project_screenshot_dm_media_id', array(
             'name' => 'project_screenshot_dm_media_id',
             'local' => 'screenshot',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('project', 'project_thumbnail_dm_media_id', array(
             'name' => 'project_thumbnail_dm_media_id',
             'local' => 'thumbnail',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('project', 'project_client_client_id', array(
             'name' => 'project_client_client_id',
             'local' => 'client',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
        $this->createForeignKey('project', 'project_client_2_client_id', array(
             'name' => 'project_client_2_client_id',
             'local' => 'client_2',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
        $this->createForeignKey('project', 'project_client_3_client_id', array(
             'name' => 'project_client_3_client_id',
             'local' => 'client_3',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
        $this->createForeignKey('project', 'project_category_id_category_id', array(
             'name' => 'project_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('project_video', 'project_video_project_project_id', array(
             'name' => 'project_video_project_project_id',
             'local' => 'project',
             'foreign' => 'id',
             'foreignTable' => 'project',
             ));
        $this->createForeignKey('service', 'service_service_category_id_service_category_id', array(
             'name' => 'service_service_category_id_service_category_id',
             'local' => 'service_category_id',
             'foreign' => 'id',
             'foreignTable' => 'service_category',
             ));
        $this->createForeignKey('staff_member', 'staff_member_photo_dm_media_id', array(
             'name' => 'staff_member_photo_dm_media_id',
             'local' => 'photo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->createForeignKey('page_dm_tag', 'page_dm_tag_dm_tag_id_dm_tag_id', array(
             'name' => 'page_dm_tag_dm_tag_id_dm_tag_id',
             'local' => 'dm_tag_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_tag',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('page_dm_tag', 'page_dm_tag_id_page_id', array(
             'name' => 'page_dm_tag_id_page_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_dm_tag', 'project_dm_tag_dm_tag_id_dm_tag_id', array(
             'name' => 'project_dm_tag_dm_tag_id_dm_tag_id',
             'local' => 'dm_tag_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_tag',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_dm_tag', 'project_dm_tag_id_project_id', array(
             'name' => 'project_dm_tag_id_project_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_dm_media', 'project_dm_media_dm_media_id_dm_media_id', array(
             'name' => 'project_dm_media_dm_media_id_dm_media_id',
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('project_dm_media', 'project_dm_media_dm_record_id_project_id', array(
             'name' => 'project_dm_media_dm_record_id_project_id',
             'local' => 'dm_record_id',
             'foreign' => 'id',
             'foreignTable' => 'project',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('client', 'client_logo', array(
             'fields' => 
             array(
              0 => 'logo',
             ),
             ));
        $this->addIndex('dm_user', 'dm_user_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->addIndex('job_application', 'job_application_resume', array(
             'fields' => 
             array(
              0 => 'resume',
             ),
             ));
        $this->addIndex('job_application', 'job_application_job_position_id', array(
             'fields' => 
             array(
              0 => 'job_position_id',
             ),
             ));
        $this->addIndex('page', 'page_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->addIndex('project', 'project_screenshot', array(
             'fields' => 
             array(
              0 => 'screenshot',
             ),
             ));
        $this->addIndex('project', 'project_thumbnail', array(
             'fields' => 
             array(
              0 => 'thumbnail',
             ),
             ));
        $this->addIndex('project', 'project_client', array(
             'fields' => 
             array(
              0 => 'client',
             ),
             ));
        $this->addIndex('project', 'project_client_2', array(
             'fields' => 
             array(
              0 => 'client_2',
             ),
             ));
        $this->addIndex('project', 'project_client_3', array(
             'fields' => 
             array(
              0 => 'client_3',
             ),
             ));
        $this->addIndex('project', 'project_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('project_video', 'project_video_project', array(
             'fields' => 
             array(
              0 => 'project',
             ),
             ));
        $this->addIndex('service', 'service_service_category_id', array(
             'fields' => 
             array(
              0 => 'service_category_id',
             ),
             ));
        $this->addIndex('staff_member', 'staff_member_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->addIndex('page_dm_tag', 'page_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->addIndex('page_dm_tag', 'page_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('project_dm_tag', 'project_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->addIndex('project_dm_tag', 'project_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('project_dm_media', 'project_dm_media_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->addIndex('project_dm_media', 'project_dm_media_dm_record_id', array(
             'fields' => 
             array(
              0 => 'dm_record_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('client', 'client_logo_dm_media_id');
        $this->dropForeignKey('dm_user', 'dm_user_photo_dm_media_id');
        $this->dropForeignKey('job_application', 'job_application_resume_dm_media_id');
        $this->dropForeignKey('job_application', 'job_application_job_position_id_job_position_id');
        $this->dropForeignKey('page', 'page_photo_dm_media_id');
        $this->dropForeignKey('project', 'project_screenshot_dm_media_id');
        $this->dropForeignKey('project', 'project_thumbnail_dm_media_id');
        $this->dropForeignKey('project', 'project_client_client_id');
        $this->dropForeignKey('project', 'project_client_2_client_id');
        $this->dropForeignKey('project', 'project_client_3_client_id');
        $this->dropForeignKey('project', 'project_category_id_category_id');
        $this->dropForeignKey('project_video', 'project_video_project_project_id');
        $this->dropForeignKey('service', 'service_service_category_id_service_category_id');
        $this->dropForeignKey('staff_member', 'staff_member_photo_dm_media_id');
        $this->dropForeignKey('page_dm_tag', 'page_dm_tag_dm_tag_id_dm_tag_id');
        $this->dropForeignKey('page_dm_tag', 'page_dm_tag_id_page_id');
        $this->dropForeignKey('project_dm_tag', 'project_dm_tag_dm_tag_id_dm_tag_id');
        $this->dropForeignKey('project_dm_tag', 'project_dm_tag_id_project_id');
        $this->dropForeignKey('project_dm_media', 'project_dm_media_dm_media_id_dm_media_id');
        $this->dropForeignKey('project_dm_media', 'project_dm_media_dm_record_id_project_id');
        $this->removeIndex('client', 'client_logo', array(
             'fields' => 
             array(
              0 => 'logo',
             ),
             ));
        $this->removeIndex('dm_user', 'dm_user_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->removeIndex('job_application', 'job_application_resume', array(
             'fields' => 
             array(
              0 => 'resume',
             ),
             ));
        $this->removeIndex('job_application', 'job_application_job_position_id', array(
             'fields' => 
             array(
              0 => 'job_position_id',
             ),
             ));
        $this->removeIndex('page', 'page_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->removeIndex('project', 'project_screenshot', array(
             'fields' => 
             array(
              0 => 'screenshot',
             ),
             ));
        $this->removeIndex('project', 'project_thumbnail', array(
             'fields' => 
             array(
              0 => 'thumbnail',
             ),
             ));
        $this->removeIndex('project', 'project_client', array(
             'fields' => 
             array(
              0 => 'client',
             ),
             ));
        $this->removeIndex('project', 'project_client_2', array(
             'fields' => 
             array(
              0 => 'client_2',
             ),
             ));
        $this->removeIndex('project', 'project_client_3', array(
             'fields' => 
             array(
              0 => 'client_3',
             ),
             ));
        $this->removeIndex('project', 'project_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('project_video', 'project_video_project', array(
             'fields' => 
             array(
              0 => 'project',
             ),
             ));
        $this->removeIndex('service', 'service_service_category_id', array(
             'fields' => 
             array(
              0 => 'service_category_id',
             ),
             ));
        $this->removeIndex('staff_member', 'staff_member_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->removeIndex('page_dm_tag', 'page_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->removeIndex('page_dm_tag', 'page_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('project_dm_tag', 'project_dm_tag_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'dm_tag_id',
             ),
             ));
        $this->removeIndex('project_dm_tag', 'project_dm_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('project_dm_media', 'project_dm_media_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->removeIndex('project_dm_media', 'project_dm_media_dm_record_id', array(
             'fields' => 
             array(
              0 => 'dm_record_id',
             ),
             ));
    }
}