generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Page
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: page
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        tags_list:
          label: Tags
        is_active:
          label: Active
      list:
        display:
          - '=title'
          - photo
          - tags_list
          - body
          - is_active
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - is_active
          - body
          - photo
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active]
          Photo: [photo_form, photo_view]
          Body: [body]
          Tags: [tags]
        class: PageAdminForm
        fields: {  }
      edit: ~
      new: ~
