<?php

/**
 * BaseDmContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property clob $body
 * @property string $email_subject
 * @property enum $email_category
 * @property string $other_desc
 * @property string $phone
 * 
 * @method string    getName()           Returns the current record's "name" value
 * @method string    getEmail()          Returns the current record's "email" value
 * @method clob      getBody()           Returns the current record's "body" value
 * @method string    getEmailSubject()   Returns the current record's "email_subject" value
 * @method enum      getEmailCategory()  Returns the current record's "email_category" value
 * @method string    getOtherDesc()      Returns the current record's "other_desc" value
 * @method string    getPhone()          Returns the current record's "phone" value
 * @method DmContact setName()           Sets the current record's "name" value
 * @method DmContact setEmail()          Sets the current record's "email" value
 * @method DmContact setBody()           Sets the current record's "body" value
 * @method DmContact setEmailSubject()   Sets the current record's "email_subject" value
 * @method DmContact setEmailCategory()  Sets the current record's "email_category" value
 * @method DmContact setOtherDesc()      Sets the current record's "other_desc" value
 * @method DmContact setPhone()          Sets the current record's "phone" value
 * 
 * @package    Funny Garbgage
 * @subpackage model
 * @author     Anthony Bovasso
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmContact extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_contact');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('email_subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_category', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'New Business',
              1 => 'Original Content',
              2 => 'Other',
             ),
             ));
        $this->hasColumn('other_desc', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}